spring.application.name=mascotas
# Verifica que el puerto 5433 sea el correcto (el default es 5432)
# Si tu base de datos tiene guiones en el nombre, asegúrate de que ya esté creada en Postgres
spring.datasource.url=jdbc:postgresql://localhost:5433/mascotas-data-base
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081

# Mostrar las consultas SQL en consola
spring.jpa.show-sql=true

# Configuración para que actualice el esquema automáticamente
spring.jpa.hibernate.ddl-auto=update

# Dialecto para PostgreSQL (Hibernate 6+ lo detecta automáticamente, pero lo dejamos corregido)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
